[userconfig]
directory = "/path/to/dir"
sent_directory = "/path/to/dir"
host = "smtp.hostname.com"
port = 465
adress = "my@mail.com"
password = "my_password"

[contacts]
person1 = "person1@mail.com"
person2 = "person2@mail.com"

